---
language: go
sudo: required

env:
  - K8S_VERSION=1.8 GIT_REV=c8ddad845a37b9f675571fc8dde1815a585e6282 HELM_VERSION=2.11.0 NUM_NODES=3 SKIP_SNAPSHOT=y PATH="$HOME/.kubeadm-dind-cluster:/tmp/linux-amd64:$PATH"

install:
  - tests/k8s-euft/helm.sh local_install
  - bats tests/k8s-euft/helm_lint.bats
  - tests/k8s-euft/bootstrap_k8s.sh
  - tests/k8s-euft/helm.sh install

script:
  # Test current version
  - bats -t tests/states/deploy.bats
  #- bats -t tests/states/delete.bats
  # Test upgrade from previous to current
  #- git checkout HEAD~
  #- bats -t tests/states/deploy.bats
  #- git checkout master
  #- bats -t tests/states/upgrade.bats

#after_script:
  #- tests/k8s-euft/clean_k8s.sh
