{{ define "elastic-alerts.rules.yaml.tpl" }}
groups:
- name: custom-node.rules
  rules:
  - alert: Elastic_UP
    expr: elasticsearch_up{job="elasticsearch"} != 1
    for: 120s
    labels:
      severity: interrupt
      serviceLevel: objective
      team: infra
      type: functional
    annotations:
      description: This server's Elasticsearch instance status has a value of {{`{{$value`}}.
      summary: Instance {{`{{$labels.instance}}`}}: Elasticsearch instance status is not 1
  - alert: Elastic_Cluster_Health_RED
    expr: elasticsearch_cluster_health_status{color="red"}==1
    for: 2m
    labels:
      severity: page
      serviceLevel: agreement
      type: functional
    annotations:
      description: Instance {{`{{$labels.instance}}`}}: not all primary and replica shards are allocated in elasticsearch cluster {{`{{$labels.cluster }}`}}.
      summary: Instance {{`{{$labels.instance}}`}}: not all primary and replica shards are allocated in elasticsearch cluster {{`{{$labels.cluster }}`}}
  - alert: Elastic_Cluster_Health_Yellow
    expr: elasticsearch_cluster_health_status{color="yellow"}==1
    for: 5m
    labels:
      severity: page
      serviceLevel: objective
      team: infra
      type: functional
    annotations:
      description: Instance {{`{{$labels.instance}}`}}: not all primary and replica shards are allocated in elasticsearch cluster {{`{{$labels.cluster }}`}}.
      summary: Instance {{`{{$labels.instance}}`}}: not all primary and replica shards are allocated in elasticsearch cluster {{`{{$labels.cluster }}`}}
  - alert: Elasticsearch_JVM_Heap_Too_High
    expr: elasticsearch_jvm_memory_used_bytes{area="heap"} / elasticsearch_jvm_memory_max_bytes{area="heap"} > 0.8
    for: 10m
    labels:
      severity: page
      serviceLevel: agreement
      type: functional
    annotations:
      description: The heap in {{`{{$labels.instance}}`}} is over 80% for 15m.
      summary: ElasticSearch node {{`{{$labels.instance}}`}} heap usage is high
{{ end }}