apiVersion: v1
kind: Service
metadata:
  name: {{ template "kubernetes.name" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    component: {{ template "kubernetes.name" . }}
    role: data
spec:
  ports:
  - port: 9300
    name: transport
  clusterIP: None
  selector:
    component: {{ template "kubernetes.name" . }}
    role: data