apiVersion: v1
kind: Service
metadata:
  name: {{ template "kubernetes.name" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubernetes.name" . }}"
    role: data
spec:
  ports:
  - port: 9300
    name: transport
  clusterIP: None
  selector:
    app: "{{ template "kubernetes.name" . }}"
    role: data