apiVersion: v1
kind: Service
metadata:
  name: {{ template "kubernetes.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "kubernetes.name" . }}
    role: client
spec:
  selector:
    app: {{ template "kubernetes.name" . }}
    role: ingest
  ports:
  - name: http
    port: 9200
    protocol: TCP
  - name: web
    port: 80
    targetPort: 9200
    protocol: TCP