{{- $esMasterVersion := .Values.elasticsearchMasterImageVersion | trunc 1 -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "kubernetes.name" . }}-master
  namespace: {{ .Release.Namespace }}
  labels:
    component: {{ template "kubernetes.name" . }}
    role: master
spec:
  replicas: {{ .Values.elasticsearchMasterReplicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: {{ template "kubernetes.name" . }}
        role: master
    spec:
      nodeSelector:
        type: {{ .Values.elasticsearchMasterNodeSelector }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: component
                operator: In
                values:
                - {{ template "kubernetes.name" . }}
              - key: role
                operator: In
                values:
                - master
            topologyKey: kubernetes.io/hostname
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: es-master
        securityContext:
          privileged: false
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        image: {{if eq $esMasterVersion "5"}}quay.io/pires/docker-elasticsearch-kubernetes{{end}}{{if eq $esMasterVersion "2"}}quay.io/mysocialapp/docker-elasticsearch-kubernetes{{end}}:{{ .Values.elasticsearchMasterImageVersion }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "CLUSTER_NAME"
          value: "{{ .Release.Namespace }}"
        - name: "NUMBER_OF_MASTERS"
          value: "{{ .Values.elasticsearchMasterQuorum }}"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_INGEST
          value: "false"
        - name: NODE_DATA
          value: "false"
        - name: HTTP_ENABLE
          value: "false"
        - name: DISCOVERY_SERVICE
          value: elasticsearch-discovery
        - name: "ES_JAVA_OPTS"
          value: "{{ .Values.elasticsearchClientJavaOptions }}"
        livenessProbe:
          tcpSocket:
            port: 9300
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: {{ template "kubernetes.name" . }}-master-storage
          mountPath: /data
      volumes:
        - name: {{ template "kubernetes.name" . }}-master-storage
          hostPath:
            path: /mnt/data/{{ .Release.Namespace }}/{{ template "kubernetes.name" . }}/master