apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana
  namespace: {{ .Release.Namespace }}
  labels:
    component: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
     component: kibana
  template:
    metadata:
      labels:
        component: kibana
    spec:
      nodeSelector:
        type: worker
      containers:
      - name: kibana
        image: quay.io/mysocialapp/docker-kibana-no-x-pack:{{ .Values.elasticsearchClientImageVersion }}
        env:
        - name: "CLUSTER_NAME"
          value: "{{ .Release.Namespace }}"
        - name: LOGGING_QUIET
          value: 'true'
        - name: XPACK_MONITORING_ENABLED
          value: 'false'
        - name: XPACK_SECURITY_ENABLED
          value: 'false'
        - name: XPACK_GRAPH_ENABLED
          value: 'false'
        - name: XPACK_ML_ENABLED
          value: 'false'
        - name: XPACK_REPORTING_ENABLED
          value: 'false'
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 5601
          name: kibana
          protocol: TCP