{{- if .Values.kibanaEnabled -}}
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: {{ .Release.Namespace }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: kibana
spec:
  selector:
    app: kibana
  ports:
  - name: http
    port: 80
    targetPort: 5601
    protocol: TCP
{{- end -}}