apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: {{ .Release.Namespace }}
  labels:
    component: kibana
spec:
  selector:
    component: kibana
  ports:
  - name: 80
    port: 5601
    protocol: TCP