### Master nodes ###

# Set where elasticsearch local data should be located
elasticsearchMasterNodeSelector: worker

# Number of nodes
elasticsearchMasterReplicaCount: 3
# Number of maximum dead nodes
elasticsearchMasterMaxUnavailableNodes: 1

# Elasticsearch common settings
elasticsearchMasterImageVersion: 2.4.5
elasticsearchMasterJavaOptions: "-Xms256m -Xmx256m"

### Data nodes ###

elasticsearchDataNodeSelector: worker
# Update deployed date to force a rolling upgrade
elasticsearchDataDeployedDate: ""

elasticsearchDataReplicaCount: 3
elasticsearchDataMaxUnavailableNodes: 1

elasticsearchDataImageVersion: 2.4.5
elasticsearchDataJavaOptions: "-Xms4g -Xmx4g"

### Client nodes ###

elasticsearchClientNodeSelector: worker

elasticsearchClientReplicaCount: 2
elasticsearchClientMaxUnavailableNodes: 1

elasticsearchClientImageVersion: 2.4.5
elasticsearchClientJavaOptions: "-Xms1g -Xmx1g"