### Elasticsearch common settings ###

elasticsearchImage: docker.elastic.co/elasticsearch/elasticsearch
elasticsearchImageVersion: 6.5.4

elasticsearchPathPrefix: "/mnt"

### Master nodes ###

# Enable Master node
elasticsearchMasterEnable: true
# Set where elasticsearch local data should be located
elasticsearchMasterNodeSelector:
  node-role.kubernetes.io/node: "true"

# Number of nodes
elasticsearchMasterReplicaCount: 3
# Number of minimum master node ( MasterReplicaCount / 2) + 1
elasticsearchMasterQuorum: 2
# Number of maximum dead nodes
elasticsearchMasterMaxUnavailableNodes: 1

elasticsearchMasterJavaOptions: "-Xms256m -Xmx256m"
elasticsearchMasterExtraVars: {}

### Data nodes ###

elasticsearchDataEnable: true
elasticsearchDataNodeSelector:
  node-role.kubernetes.io/node: "true"

elasticsearchDataReplicaCount: 3
elasticsearchDataMaxUnavailableNodes: 1

elasticsearchDataJavaOptions: "-Xms1g -Xmx1g"
elasticsearchDataExtraVars: {}
elasticsearchDataUseCustomConfig: {}
#  elasticsearch.yml: false
#  jvm.options: false
#  log4j2.properties: false

### Ingest nodes ###

elasticsearchIngestEnable: true
elasticsearchIngestNodeSelector:
  node-role.kubernetes.io/node: "true"

elasticsearchIngestReplicaCount: 2
elasticsearchIngestMaxUnavailableNodes: 1

elasticsearchIngestJavaOptions: "-Xms1g -Xmx1g"
elasticsearchIngestExtraVars: {}
elasticsearchIngestResources: {}
#  limits:
#    memory: 4G
#    cpu: 500m
#  requests:
#    memory: 4G
#    cpu: 500m

### Elasticsearch Exporter ###

elasticsearchExporter:
  exporterEnable: false
  exporterReplicas: 1
  exporterNodeSelector:
    node-role.kubernetes.io/node: "true"
    stateless: "true"
  exporterImageRepository: justwatch/elasticsearch_exporter
  exporterImageTag: 1.0.2
  exporterUri: http://elasticsearch:9200
  exporterAll: true
  exporterIndices: true
  exporterTimeout: 59s
  exporterPort: 9108
  resources:
    limits:
      cpu: 300m
      memory: 100M
    requests:
      cpu: 200m
      memory: 64M

### Prometheus scraping & alerting ###

elasticsearchPrometheusScrap: false
elasticsearchAlertmanager:
  alertsEnabled: false
  alertLabels:
    sloInterrupt:
      serviceLevel: objective
      severity: interrupt
      team: infra
      type: functional
    sloPage:
      serviceLevel: objective
      severity: page
      team: infra
      type: functional

### Kibana ###

kibanaEnabled: false
kibanaImage: docker.elastic.co/kibana/kibana
kibanaNodeSelector:
  node-role.kubernetes.io/node: "true"
  stateless: "true"
kibanaExtraVars: {}
kibanaResources: {}
#  limits:
#    cpu: 500m
#    memory: 768M
#  requests:
#    cpu: 300m
#    memory: 256M
