### Master nodes ###

# Set where elasticsearch local data should be located
elasticsearchMasterNodeSelector:
  node-role.kubernetes.io/node: "true"

# Number of nodes
elasticsearchMasterReplicaCount: 3
# Number of minimum master node ( MasterReplicaCount / 2) + 1
elasticsearchMasterQuorum: 2
# Number of maximum dead nodes
elasticsearchMasterMaxUnavailableNodes: 1

# Elasticsearch common settings
elasticsearchMasterImageVersion: 5.6.9
elasticsearchMasterJavaOptions: "-Xms256m -Xmx256m"

### Data nodes ###

elasticsearchDataNodeSelector:
  node-role.kubernetes.io/node: "true"

elasticsearchDataReplicaCount: 3
elasticsearchDataMaxUnavailableNodes: 1

elasticsearchDataImageVersion: 5.6.9
elasticsearchDataJavaOptions: "-Xms4g -Xmx4g"

### Client nodes ###

elasticsearchClientNodeSelector:
  node-role.kubernetes.io/node: "true"

elasticsearchClientReplicaCount: 2
elasticsearchClientMaxUnavailableNodes: 1

elasticsearchClientImageVersion: 5.6.9
elasticsearchClientJavaOptions: "-Xms1g -Xmx1g"

### Elasticsearch Exporter ###

elasticsearchExporter:
  exporterEnable: false
  exporterReplicas: 1
  exporterImageRepository: justwatch/elasticsearch_exporter
  exporterImageTag: 1.0.2
  exporterUri: http://elasticsearch:9200
  exporterAll: true
  exporterIndices: true
  exporterTimeout: 59s
  exporterPort: 9108
elasticsearchPrometheusScrap: false
elasticsearchAlertmanager: false

### Kibana ###

kibanaEnabled: true
#kibanaImage: kibana
#kibanaVersion: 4.6.6
kibanaNodeSelector:
  node-role.kubernetes.io/node: "true"